### ISSUE TITLE
Cannot import checkout_sdk with the latest version (3.0.19)

### ISSUE THREAD

**Issue by k4nar** [checkout/checkout-sdk-python#152]
### Environment

* Checkout SDK version: 3.0.19
* Platform and version: Any
* Operating System and version: Any

### Description
Importing `checkout_sdk` results in an error with version 3.0.19.

### Current behavior
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/checkout/lib/python3.11/site-packages/checkout_sdk/__init__.py", line 3, in <module>
    from checkout_sdk.checkout_sdk import CheckoutSdk # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/checkout/lib/python3.11/site-packages/checkout_sdk/checkout_sdk.py", line 3, in <module>
    from checkout_sdk.default_sdk import DefaultSdk
  File "/tmp/checkout/lib/python3.11/site-packages/checkout_sdk/default_sdk.py", line 5, in <module>
    from checkout_sdk.checkout_api import CheckoutApi
  File "/tmp/checkout/lib/python3.11/site-packages/checkout_sdk/checkout_api.py", line 15, in <module>
    from checkout_sdk.payments.sessions.sessions_client import PaymentSessionsClient
ModuleNotFoundError: No module named 'checkout_sdk.payments.sessions'
```

### Steps to reproduce
```
$ pip install checkout-sdk==3.0.19
$ python -c 'import checkout_sdk'
```

### Possible solution

Probably introduced by #148.
I think that a `__init__.py` file is missing in `checkout_sdk/payments/sessions`.

**Comment by armando-rodriguez-cko** [comment]
Thank you @k4nar! We will fix it.
